name: achadinhos-tunnels

services:
  cloudflared-dev:
    image: cloudflare/cloudflared:2026.3.0
    container_name: achadinhos-cloudflared-dev
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config/config.dev.yml --metrics 0.0.0.0:2011 run
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:2011:2011"
    volumes:
      - type: bind
        source: ${CLOUDFLARED_CRED_DIR}
        target: /etc/cloudflared/creds
        read_only: true
      - type: bind
        source: ./cloudflared/generated/config.dev.yml
        target: /etc/cloudflared/config/config.dev.yml
        read_only: true

  cloudflared-prod:
    image: cloudflare/cloudflared:2026.3.0
    container_name: achadinhos-cloudflared-prod
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config/config.prod.yml --metrics 0.0.0.0:2012 run
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:2012:2012"
    volumes:
      - type: bind
        source: ${CLOUDFLARED_CRED_DIR}
        target: /etc/cloudflared/creds
        read_only: true
      - type: bind
        source: ./cloudflared/generated/config.prod.yml
        target: /etc/cloudflared/config/config.prod.yml
        read_only: true

